import { spawn } from 'node:child_process';
import { redact } from '@luoshu/config/security';
export interface OpenCodeInput { cwd:string; prompt:string; executable?:string; signal?:AbortSignal; killGraceMs?:number; onProgress?:(text:string)=>void;onSession?:(id:string)=>void; env?:Record<string,string> }
export interface OpenCodeResult { exitCode:number; summary:string; checks:{command:string;exit_code:number;output:string}[]; events:unknown[]; argv:string[]; sessionId?:string }
const clip=(value:string,max=16000)=>redact(value).slice(0,max);
export async function runOpenCode(input:OpenCodeInput):Promise<OpenCodeResult>{
 const argv=['run','--format','json','--dir',input.cwd];if(input.signal?.aborted)return{exitCode:130,summary:'Execution cancelled before process start',checks:[],events:[],argv};
 const child=spawn(input.executable??'opencode',argv,{cwd:input.cwd,stdio:['pipe','pipe','pipe'],detached:true,env:{...process.env,...input.env}});const events:unknown[]=[];let pending='',stderr='',summary='',sessionId:string|undefined,failed=false;let killTimer:ReturnType<typeof setTimeout>|undefined;let termination:Promise<void>|undefined;
 const consume=(line:string)=>{if(!line||line.length>65_536)return;let event:any;try{event=JSON.parse(line);}catch{return;}if(!event||typeof event!=='object'||Array.isArray(event))return;if(events.length<1000)events.push(event);const session=event.sessionID??event.session_id;if(!sessionId&&typeof session==='string'){sessionId=clip(session,200);input.onSession?.(sessionId);}const text=event.type==='text'&&typeof event.part?.text==='string'?event.part.text:undefined;if(text){summary=clip(summary+text);input.onProgress?.(clip(text,8000));}const error=event.type==='error'?(typeof event.error==='string'?event.error:event.error?.message??event.error?.data?.message??event.message):event.type==='tool_use'&&event.part?.state?.status==='error'?event.part.state.error:undefined;if(error){failed=true;summary=clip(summary+String(error));}if(event.type==='permission'&&(event.status==='denied'||event.part?.status==='denied')){failed=true;summary=clip(summary+(event.message??'Permission denied'));}if(event.type==='warning'&&event.code==='permission_auto_rejected'){failed=true;summary=clip(summary+(event.message??'Permission auto-rejected'));}};
 const terminate=()=>{if(termination)return;try{process.kill(-child.pid!,'SIGTERM');}catch{}termination=new Promise<void>(resolve=>{killTimer=setTimeout(()=>{try{process.kill(-child.pid!,'SIGKILL');}catch{}resolve();},input.killGraceMs??3000);});};input.signal?.addEventListener('abort',terminate,{once:true});child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',(chunk:string)=>{pending+=chunk;if(pending.length>131_072)pending=pending.slice(-65_536);let i:number;while((i=pending.indexOf('\n'))>=0){consume(pending.slice(0,i));pending=pending.slice(i+1);}});child.stderr.on('data',(chunk:string)=>{stderr=clip(stderr+chunk,8000);});child.stdin.on('error',()=>undefined);child.stdin.end(input.prompt);
 let exitCode=await new Promise<number>(resolve=>{let settled=false;const done=(code:number)=>{if(!settled){settled=true;resolve(code);}};child.once('error',()=>done(1));child.once('close',code=>done(code??1));});consume(pending);input.signal?.removeEventListener('abort',terminate);await termination;if(killTimer)clearTimeout(killTimer);if(input.signal?.aborted){failed=true;exitCode=exitCode||130;}if(!summary.trim()){failed=true;summary=stderr||'OpenCode produced no result';}if(failed&&exitCode===0)exitCode=1;return{exitCode,summary:clip(summary),checks:[],events,argv,sessionId};
}
