import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect,test } from 'vitest';
import { saveWorkerConfig } from '../src/environment.js';
const exec=promisify(execFile);
const run=(...args:string[])=>exec(process.execPath,['--import','tsx','apps/worker/src/main.ts',...args]);
const runFromRoot=(...args:string[])=>exec('npm',['run','worker','--',...args],{cwd:process.cwd()});
test('CLI rejects local Agent authorization and removed configuration commands',async()=>{await expect(run('join','--agents','codex')).rejects.toMatchObject({stderr:expect.stringContaining('Unknown')});await expect(run('join','--scopes','personal')).rejects.toMatchObject({stderr:expect.stringContaining('Unknown')});await expect(run('configure','--state','/tmp/unused')).rejects.toMatchObject({stderr:expect.stringContaining('join|agents|run')});});
test('agent detection is read-only and supports executable path configuration only',async()=>{const dir=await mkdtemp(join(tmpdir(),'luoshu-agent-cli-'));await saveWorkerConfig(dir,{worker_id:'w',url:'https://example.test',name:'desk',capacity:1,agent_paths:{codex:'/missing/codex',opencode:'/missing/opencode'}});const before=await readFile(join(dir,'config.json'),'utf8');await run('agents','--state',dir);expect(await readFile(join(dir,'config.json'),'utf8')).toBe(before);await expect(run('agents','--state',dir,'--enable','codex')).rejects.toMatchObject({stderr:expect.stringContaining('Unknown')});});
test('root worker script forwards named CLI arguments unchanged',async()=>{const dir=await mkdtemp(join(tmpdir(),'luoshu-root-worker-cli-'));await saveWorkerConfig(dir,{worker_id:'w',url:'https://example.test',name:'desk',capacity:1,agent_paths:{codex:'/missing/codex',opencode:'/missing/opencode'}});const result=await runFromRoot('agents','--state',dir);expect(JSON.parse(result.stdout.trim().split('\n').at(-1)!)).toMatchObject({name:'desk',protocol_version: 8});});
