import {z} from 'zod';
import {idSchema,positive,text,agentIdSchema} from './wire-base.js';
import {taskFilesSchema} from './task-files.js';
const uuidSchema=z.string().uuid();
const shaSchema=z.string().regex(/^[a-f0-9]{40,64}$/);
const aliasSchema=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/);
const relativePathSchema=z.string().min(1).max(500).refine(value=>!value.startsWith('/')&&!value.split('/').includes('..')&&!/[\u0000-\u001f\u007f]/.test(value),'Invalid relative path');
export const codebaseSourceSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('git'),repository_url:z.string().min(1).max(2048)}).strict(),
 z.object({kind:z.literal('local'),path:z.string().min(1).max(4096).startsWith('/')}).strict(),
]);
export const codebaseAssignmentSchema=z.object({id:uuidSchema,alias:aliasSchema,access_mode:z.enum(['write','read']),source:codebaseSourceSchema,root_path:relativePathSchema,default_branch:text(200),base_commit:shaSchema,branch:z.string().regex(/^luoshu\/(?:feature|repair|verify)\/[A-Za-z0-9._-]+$/).nullable()}).strict().superRefine((value,context)=>{if(value.access_mode==='read'&&value.branch!==null)context.addIssue({code:'custom',path:['branch'],message:'Read Codebase cannot have a branch'});if(value.access_mode==='write'&&value.branch===null)context.addIssue({code:'custom',path:['branch'],message:'Write Codebase requires a branch'});});
export type CodebaseAssignment=z.infer<typeof codebaseAssignmentSchema>;
export const codebasePrepareSpecSchema=z.object({id:uuidSchema,alias:aliasSchema,access_mode:z.enum(['write','read']),source:codebaseSourceSchema,root_path:relativePathSchema,default_branch:text(200),branch:z.string().regex(/^luoshu\/(?:feature|repair|verify)\/[A-Za-z0-9._-]+$/).nullable()}).strict().superRefine((value,context)=>{if(value.access_mode==='read'&&value.branch!==null)context.addIssue({code:'custom',path:['branch'],message:'Read Codebase cannot have a branch'});if(value.access_mode==='write'&&value.branch===null)context.addIssue({code:'custom',path:['branch'],message:'Write Codebase requires a branch'});});
export type CodebasePrepareSpec=z.infer<typeof codebasePrepareSpecSchema>;
export const codebasePrepareRequestSchema=z.object({type:z.literal('codebase_prepare_request'),request_id:idSchema,run_id:idSchema,codebases:z.array(codebasePrepareSpecSchema).min(1).max(32)}).strict();
export type CodebasePrepareRequest=z.infer<typeof codebasePrepareRequestSchema>;
export const codebasePrepareResultSchema=z.object({codebase_id:uuidSchema,base_commit:shaSchema,branch:z.string().max(200).nullable(),checkout_path:z.string().min(1).max(4096),read_isolation:z.literal('enforced').optional()}).strict();
export type CodebasePrepareResult=z.infer<typeof codebasePrepareResultSchema>;
export const codebasePrepareResponseSuccessSchema=z.object({type:z.literal('codebase_prepare_response'),request_id:idSchema,run_id:idSchema,codebases:z.array(codebasePrepareResultSchema).min(1).max(32)}).strict();
export const codebasePrepareResponseErrorSchema=z.object({type:z.literal('codebase_prepare_response'),request_id:idSchema,run_id:idSchema,error:text(2000)}).strict();
export type CodebasePrepareResponse=z.infer<typeof codebasePrepareResponseSuccessSchema>|z.infer<typeof codebasePrepareResponseErrorSchema>;
export const codebaseExecutionResultSchema=z.object({codebase_id:uuidSchema,access_mode:z.enum(['write','read']),head_commit:shaSchema.nullable(),branch:z.string().max(200).nullable(),result:z.enum(['unchanged','changed','failed','unknown']),changed_paths:z.array(relativePathSchema).max(500),read_isolation:z.literal('enforced').optional()}).strict().superRefine((value,context)=>{if(value.access_mode==='read'&&(value.head_commit!==null||value.branch!==null||value.result==='changed'||value.changed_paths.length||value.read_isolation!=='enforced'))context.addIssue({code:'custom',message:'Read Codebase result must be unchanged and isolated'});if(value.access_mode==='write'&&value.result==='changed'&&(!value.head_commit||!value.branch))context.addIssue({code:'custom',message:'Changed write Codebase requires a commit and branch'});});
export type CodebaseExecutionResult=z.infer<typeof codebaseExecutionResultSchema>;
export const assignmentSchema=z.object({attempt_id:idSchema,lease_epoch:positive,agent:agentIdSchema,instruction:text(64000),input_files:taskFilesSchema,run_id:idSchema.optional(),codebases:z.array(codebaseAssignmentSchema).max(32).default([]),timeout_seconds:z.number().int().min(1).max(7200).nullable()}).strict().superRefine((value,context)=>{if(value.codebases.length&&!value.run_id)context.addIssue({code:'custom',path:['run_id'],message:'Codebase assignments require a Run ID'});if(new Set(value.codebases.map(item=>item.id)).size!==value.codebases.length)context.addIssue({code:'custom',path:['codebases'],message:'Duplicate Codebase IDs'});if(new Set(value.codebases.map(item=>item.alias)).size!==value.codebases.length)context.addIssue({code:'custom',path:['codebases'],message:'Duplicate Codebase aliases'});});
export type Assignment=z.infer<typeof assignmentSchema>;
export const resultSchema=z.object({status:z.enum(['succeeded','failed','cancelled','blocked']),summary:z.string().max(16000),checks:z.array(z.object({command:text(2000),exit_code:z.number().int(),output:z.string().max(8000)}).strict()).max(50).default([]),files:taskFilesSchema.optional(),agent:agentIdSchema,session_id:z.string().max(200).optional(),error:z.string().max(2000).optional(),codebases:z.array(codebaseExecutionResultSchema).max(32).default([])}).strict().superRefine((value,context)=>{if(new Set(value.codebases.map(item=>item.codebase_id)).size!==value.codebases.length)context.addIssue({code:'custom',path:['codebases'],message:'Duplicate Codebase results'});});
export type ExecutionResult=z.infer<typeof resultSchema>;
